[tool.poetry]
name = "django-devdata"
version = "0.1.1"
description = ""
authors = ["Dan Palmer <dan@danpalmer.me>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/danpalmer/django-devdata"
keywords = [ "django", "development", "databases" ]
packages = [
    { include = "devdata", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.5"

[tool.poetry.dev-dependencies]
black = [
    {version = "*", python = "^3.6"}
]
flake8 = "^3.8.4"
flake8-black = "^0.2.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
