[tool.poetry]
name = "django-devdata"
version = "0.1.1"
description = ""
authors = ["Dan Palmer <dan@danpalmer.me>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/danpalmer/django-devdata"
keywords = [ "django", "development", "databases" ]
packages = [
    { include = "devdata", from = "src" },
]

[tool.poetry.dependencies]
python = ">=3.6.1"

[tool.poetry.dev-dependencies]
black = "*"
flake8 = "*"
flake8-black = "*"
flake8-github-actions = "^0.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
